### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [awslabs/fhir-works-on-aws-authz-smart#17]
For installing this it says...
To use and deploy this component (with the other 'out of the box' components) please follow the overall README

...which doesn't make mention of the SMART auth.

I do notice a branch called authz-smart. Are the instructions to switch to that branch then run the install? Any other things to keep in mind?

**Comment by rsmayda** [comment]
This package and the SMART feature is still a work in progress. Documentation has not been worked on yet - We aim to have documentation complete in the coming month.

**Comment by rsmayda** [comment]
Updated!

To use and deploy this component please follow the overall [`smart-mainline` branch README](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/smart-mainline)
