### ISSUE TITLE
Making custom health card operations

### ISSUE THREAD

**Issue by gopalp19** [awslabs/fhir-works-on-aws-authz-smart#29]
My team is trying to make a SMART Health cards implementation using FHIR Works. As part of the implementation, we need an ability to create custom extended operations, so that we can issue health cards as part of a Patient request (POST /Patient/:id/$health-cards-issue). Has anyone done this before?  Or can provide some guidance on how to accomplish such a task?

The pattern we're following is defined here:
https://smarthealth.cards/#via-fhir-health-cards-issue-operation

**Comment by rsmayda** [comment]
Super interesting use-case. I do not know of anyone doing this. At face value this seems to be more of a authentication feature than a FHIR one. I would probably focus on building a small lambda that takes in a verifiable JWT from an idP and then calls a FHIR server to determine if that user can have a HealthCard created. 

One question I wasn't able to answer is do we need to track the HealthCards created? Do HealthCards need to be revoked?

Another path forward: If you want Update the router to handle this new endpoint -- could get started somewhere here: https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/routes/genericResourceRoute.ts#L34

Like I said I would suggest to keep this feature outside of the FHIR server but happy to chat more

**Comment by gopalp19** [comment]
Thanks for the quick follow-up @rsmayda!

My understanding was that since we needed to create an endpoint built on top of the original /Patient/:id this would require changes to the FHIR Server. Specifically, it looks like we want an "Extended Operation" (https://www.hl7.org/fhir/operations.html) for "$health-cards-issue". On first pass it looked like FHIR Works had Operations, and I thought we could just add this new operation in somewhere. 

The SMART Health Cards framework has an Operation defined here: https://smarthealth.cards/artifacts/operation-patient-i-health-cards-issue.json

I'll take a look at the router, that does look like the starting point. And to answer your Q, I think there might need to be some type of auditing trail for health card access. I don't think revoking is a feature tho.

**Comment by rsmayda** [comment]
So the nice thing about serverless is you could have another lambda accepting this specific request. https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L78-L88

in the `path` parameter you could have something like `/Patient/{id}/$health-cards-issue` and `method` set to `POST`. Just a thought 👍

**Comment by gopalp19** [comment]
Ah that could work! I'll play around with it and see what I can get.

We also thought about creating some sort of proxy within API Gateway, that would route requests to another lambda.

**Comment by gopalp19** [comment]
@rsmayda If we take this approach, is it as simple as, modifying the fhir-works-on-aws-deployment package to include this new request. But then point the handler to another package/folder/repo?

I'm thinking it's prob best to modify the original FHIR Works solution as little as possible, and just have this custom lambda be more of an extension (e.g. we just need to deploy the lambda code each time it has changed vs having to redeploy the FHIR Works package/s each time).

**Comment by rsmayda** [comment]
There are a few 'gotchas' like:
- the order of the declared API GW paths should be most specific to least specific (ie list your custom path, should be first)
- AuthN/AuthZ will have to be custom (or you can rely on communication to FWoA instance)

I am sure there may be others, you discover along the path

But overall yeah it is that "simple"

> I'm thinking it's prob best to modify the original FHIR Works solution as little as possible

100% agree with you it will make merging in new changes from us much easier :)

**Comment by gopalp19** [comment]
Got it, thanks!

A little unrelated Q. I know the default FHIR works uses cognito as the auth component. Is it easy to switch this out to another identity provider (thinking okta or id.me)?

**Comment by rsmayda** [comment]
For the default role based access control repo (https://github.com/awslabs/fhir-works-on-aws-authz-rbac) it wasn't built for the purpose to be flexible. That said you could use that as your base and adjust from there. 

Another option is to use the SMART AuthZ package which *was* built for flexibility: https://github.com/awslabs/fhir-works-on-aws-authz-smart. In this case you just need to pass in OAuth2 and patient_picker information - so really any modern idP would work in this situation.
