### ISSUE TITLE
Allow for the FHIRUserClaim and PatientContextClaim to be pulled from other than root of token

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-authz-smart#39]
**Is your feature request related to a problem? Please describe.**
Our auth server only allows for these to be placed under the ext section of the token.

**Describe the solution you'd like**
Allow for a path to be placed as a variable or coded so it can easily be added or changed if needed for other auth servers.

**Additional context**
Currently it is like this const fhirUserClaim = decodedToken[this.config.fhirUserClaimKey]; for our auth server to work we would have to use const fhirUserClaim = decodedToken.ext[this.config.fhirUserClaimKey];

**Comment by rsmayda** [comment]
Looking into this now!
