### ISSUE TITLE
[Misc] Default configuration makes a Practitioner an admin

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-authz-smart#58]
**What's on your mind?**
The default configuration makes a Practitioner an admin. Could you tell me how I can change the configuration in order to make a Practitioner not an admin ?

Thanks in advance

**Versions (please complete the following information):**
 - v2.2.2

**Comment by nguyen102** [comment]
[SmartHandler](https://github.com/awslabs/fhir-works-on-aws-authz-smart/blob/mainline/src/smartHandler.ts#L79) accepts a parameter called `adminAccessTypes` and by default it's set to `Practitioner`. You can pass in a different value for that to change the setting for it.

You can pass a new value for that setting on this [line](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/src/config.ts#L54) in the deployment package.

**Comment by lquanx** [comment]
Thanks very much !
