### ISSUE TITLE
[Bug] _include issue when system scopes are not set to *

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-authz-smart#78]
**Describe the bug**
An issue occurs when we have specific system scopes specified (Ex. system/DocumentReference.read and system/Patient.read, no system/*.read it will only return the resource that was requested and it filters out all of the included resources.
 
Example: We request a DocumentReference and do an _include to get the Patient resource.
 
If we have system/DocumentReference.read and system/Patient.read as scopes, it will only return the DocumentReference resource. If we have system/*.read it will return both. It appears to be in the getValidOperationsForScope function in smartScopeHelper.ts.  The hasAccessToResource function filters the included Patient out because only DocumentReference is in the usable scopes.

**Expected behavior**
The expected result would be for it to check against the full list of scopes to see if it was valid.

**Comment by ssvegaraju** [comment]
Hi @medhost-gkersting, just wanted to reach out to let you know that a fix for this issue has been merged in! Thanks for bringing up this issue, I'll go ahead close it but feel free to reopen if there's anything else!
