### ISSUE TITLE
Assumptions met but requests are unauthorized

### ISSUE THREAD

**Issue by sdan22** [awslabs/fhir-works-on-aws-authz-smart#84]
I am using v3.1.1 from the deployment package version v2.4.0-smart from the smart-mainline branch. I created the example patient resource in the README and I have attempted a few ways to do a GET on the Patient resourceType.
 
Based on the README, my request should be accessible due to the claims in my access token. Also the scopes in my access token `patient/Patient.read` maps to `scopeRule.patient.read` operations. So I am unsure why my requests are coming back as unauthorized. 

My claims:
"launch_response_patient": "Patient/example",
"fhirUser": "https://xxxxxxxx.execute-api.us-west-1.amazonaws.com/sandbox/Patient/example"
 
My Scopes:
  "scp": [
    "fhirUser",
    "openid",
    "patient/Patient.read",
    "launch/patient",
    "profile"
  ],

Request:
Request: GET https://xxxxxxxx.execute-api.us-west-1.amazonaws.com/sandbox/Patient/example?access_token=eyJ

**Comment by nguyen102** [comment]
Hi @sdan22,

This is an example of our decoded jwt token.

```
{
  "ver": 1,
  "jti": "AT.*********dA",
  "iss": "https://dev-*******.okta.com/oauth2/*******",
  "aud": "https://*******.execute-api.us-east-2.amazonaws.com/dev",
  "iat": 1650641331,
  "exp": 1650644931,
  "cid": "*******",
  "uid": "******",
  "scp": [
    "fhirUser",
    "user/*.*"
  ],
  "auth_time": 1650641331,
  "sub": "******@amazon.com",
  "tenantId": "tenant1",
  "fhirUser": "https://*****.execute-api.us-east-2.amazonaws.com/dev/Practitioner/*****"
}
```

You can see how we get the access token by taking a look at our test code. The test requests an access token and you can use that access token as needed in POSTMAN. The test code is [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/3ed101babe86845d8148e0e7c0836cc908fe8449/integration-tests/bulkExport.test.ts#L17). You can keep the code in the `beforeAll` section, but comment out all of the other test code. Then be sure to`console.log` the `accessToken` [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/3ed101babe86845d8148e0e7c0836cc908fe8449/integration-tests/utils.ts#L112). You will need to provide the environment variables listed between line 58 and 67.

**Comment by sdan22** [comment]
Hi @nguyen102,

Thank you this will help me troubleshoot the issue!
