### ISSUE TITLE
[Misc] token revocation

### ISSUE THREAD

**Issue by liquid36** [awslabs/fhir-works-on-aws-authz-smart#86]
Hi!
I want to know if you have something about token revocation? I know that is a task for the authentication server but when a revoke a token i can still use it against the API because there is not any communication between the fhir server and the auth server. 

 
Thanks

**Comment by nguyen102** [comment]
Hi @liquid36,

We currently do not have token revocation implemented.

**Comment by liquid36** [comment]
Okey, thank you! 

For now, i created an AWS Authorizer to get the job done.
